const characters_order_priority = {
    0: "Aether",
    1: "Lumine",
    2: "Sucrose",
    3: "Keqing",
    4: "Mona",
    5: "Chongyun",
    6: "Qiqi",
    7: "Noelle",
    8: "Bennett",
    9: "Fischl",
    10: "Ningguang",
    11: "Xingqiu",
    12: "Beidou",
    13: "Xiangling",
    14: "Venti",
    15: "Amber",
    16: "Razor",
    17: "Diluc",
    18: "Kaeya",
    19: "Barbara",
    20: "Lisa",
    21: "Jean",
    22: "Diona",
    23: "Klee",
    24: "Tartaglia",
    25: "Xinyan",
    26: "Zhongli",
    27: "Albedo",
    28: "Ganyu",
    29: "Xiao",
    30: "Hu Tao",
    31: "Rosaria",
    32: "Yanfei",
    33: "Eula",
    34: "Kaedehara Kazuha",
    35: "Kamisato Ayaka",
    36: "Sayu",
    37: "Yoimiya",
    38: "Aloy",
    39: "Kujou Sara",
    40: "Raiden Shogun",
    41: "Sangonomiya Kokomi",
    42: "Thoma",
    43: "Arataki Itto",
    44: "Gorou",
    45: "Yun Jin",
    46: "Shenhe",
    47: "Yae Miko",
    48: "Kamisato Ayato",
    49: "Yelan",
    50: "Kuki Shinobu",
    51: "Shikanoin Heizou",
    52: "Tighnari",
    53: "Collei",
    54: "Dori",
    55: "Candace",
    56: "Cyno",
    57: "Nilou",
    58: "Nahida",
    59: "Layla",
    60: "Faruzan",
    61: "Wanderer",
    62: "Alhaitham",
    63: "Yaoyao",
    64: "Dehya",
    65: "Mika",
    66: "Baizhu",
    67: "Kaveh",
    68: "Kirara",
    69: "Lyney",
    70: "Lynette",
    71: "Freminet",
    72: "Neuvillette",
    73: "Wriothesley",
    74: "Furina",
    75: "Charlotte",
    76: "Navia",
    77: "Chevreuse",
    78: "Xianyun",
    79: "Gaming",
    80: "Chiori",
    81: "Arlecchino"
}