const characters_signature_weapons = {
    "Aether": "",
    "Lumine": "",
    "Sucrose": "",
    "Keqing": "Primordial Jade Cutter",
    "Mona": "",
    "Chongyun": "",
    "Qiqi": "",
    "Noelle": "",
    "Bennett": "",
    "Fischl": "",
    "Ningguang": "",
    "Xingqiu": "",
    "Beidou": "",
    "Xiangling": "",
    "Venti": "Elegy for the End",
    "Amber": "",
    "Razor": "",
    "Diluc": "Wolf's Gravestone",
    "Kaeya": "",
    "Barbara": "",
    "Lisa": "",
    "Jean": "",
    "Diona": "",
    "Klee": "Skyward Atlas",
    "Tartaglia": "Polar Star",
    "Xinyan": "",
    "Zhongli": "Vortex Vanquisher",
    "Albedo": "Summit Shaper",
    "Ganyu": "Amos' Bow",
    "Xiao": "Primordial Jade Winged-Spear",
    "Hu Tao": "Staff of Homa",
    "Rosaria": "",
    "Yanfei": "",
    "Eula": "Song of Broken Pines",
    "Kaedehara Kazuha": "Freedom-Sworn",
    "Kamisato Ayaka": "Mistsplitter Reforged",
    "Sayu": "",
    "Yoimiya": "Thundering Pulse",
    "Aloy": "",
    "Kujou Sara": "",
    "Raiden Shogun": "Engulfing Lightning",
    "Sangonomiya Kokomi": "Everlasting Moonglow",
    "Thoma": "",
    "Arataki Itto": "Redhorn Stonethresher",
    "Gorou": "",
    "Yun Jin": "",
    "Shenhe": "Calamity Queller",
    "Yae Miko": "Kagura's Verity",
    "Kamisato Ayato": "Haran Geppaku Futsu",
    "Yelan": "Aqua Simulacra",
    "Kuki Shinobu": "",
    "Shikanoin Heizou": "",
    "Tighnari": "Hunter's Path",
    "Collei": "",
    "Dori": "",
    "Candace": "",
    "Cyno": "Staff of the Scarlet Sands",
    "Nilou": "Key of Khaj-Nisut",
    "Nahida": "A Thousand Floating Dreams",
    "Layla": "",
    "Faruzan": "",
    "Wanderer": "Tulaytullah's Remembrance",
    "Alhaitham": "Light of Foliar Incision",
    "Yaoyao": "",
    "Dehya": "Beacon of the Reed Sea",
    "Mika": "",
    "Baizhu": "Jadefall's Splendor",
    "Kaveh": "",
    "Kirara": "",
    "Lyney": "The First Great Magic",
    "Lynette": "",
    "Freminet": "",
    "Neuvillette": "Tome of the Eternal Flow",
    "Wriothesley": "Cashflow Supervision",
    "Furina": "Splendor of Tranquil Waters",
    "Charlotte": "",
    "Navia": "Verdict",
    "Chevreuse": "",
    "Xianyun": "Crane's Echoing Call",
    "Gaming": "",
    "Chiori": "Uraku Misugiri",
    "Arlecchino": "Crimson Moon's Semblance"
}