const weapons = {
    "A Thousand Floating Dreams": {},
    "Amos' Bow": {},
    "Aqua Simulacra": {},
    "Aquila Favonia": {},
    "Beacon of the Reed Sea": {},
    "Calamity Queller": {},
    "Cashflow Supervision": {},
    "Crane's Echoing Call": {},
    "Elegy for the End": {},
    "Engulfing Lightning": {},
    "Everlasting Moonglow": {},
    "Freedom-Sworn": {},
    "Haran Geppaku Futsu": {},
    "Hunter's Path": {},
    "Jadefall's Splendor": {},
    "Kagura's Verity": {},
    "Key of Khaj-Nisut": {},
    "Light of Foliar Incision": {},
    "Lost Prayer to the Sacred Winds": {},
    "Memory of Dust": {},
    "Mistsplitter Reforged": {},
    "Polar Star": {},
    "Primordial Jade Cutter": {},
    "Primordial Jade Winged-Spear": {},
    "Redhorn Stonethresher": {},
    "Skyward Atlas": {},
    "Skyward Blade": {},
    "Skyward Harp": {},
    "Skyward Pride": {},
    "Skyward Spine": {},
    "Song of Broken Pines": {},
    "Splendor of Tranquil Waters": {},
    "Staff of Homa": {},
    "Staff of the Scarlet Sands": {},
    "Summit Shaper": {},
    "The First Great Magic": {},
    "The Unforged": {},
    "Thundering Pulse": {},
    "Tome of the Eternal Flow": {},
    "Tulaytullah's Remembrance": {},
    "Verdict": {},
    "Vortex Vanquisher": {},
    "Wolf's Gravestone": {},
    "\"The Catch\"": {},
    "\"Ultimate Overlord's Mega Magic Sword\"": {},
    "Akuoumaru": {},
    "Alley Hunter": {},
    "Amenoma Kageuchi": {},
    "Ballad of the Boundless Blue": {},
    "Ballad of the Fjords": {},
    "Blackcliff Agate": {},
    "Blackcliff Longsword": {},
    "Blackcliff Pole": {},
    "Blackcliff Slasher": {},
    "Blackcliff Warbow": {},
    "Cinnabar Spindle": {},
    "Compound Bow": {},
    "Crescent Pike": {},
    "Deathmatch": {},
    "Dodoco Tales": {},
    "Dragon's Bane": {},
    "Dragonspine Spear": {},
    "End of the Line": {},
    "Eye of Perception": {},
    "Fading Twilight": {},
    "Favonius Codex": {},
    "Favonius Greatsword": {},
    "Favonius Lance": {},
    "Favonius Sword": {},
    "Favonius Warbow": {},
    "Festering Desire": {},
    "Finale of the Deep": {},
    "Fleuve Cendre Ferryman": {},
    "Flowing Purity": {},
    "Forest Regalia": {},
    "Frostbearer": {},
    "Fruit of Fulfillment": {},
    "Hakushin Ring": {},
    "Hamayumi": {},
    "Ibis Piercer": {},
    "Iron Sting": {},
    "Kagotsurube Isshin": {},
    "Katsuragikiri Nagamasa": {},
    "King's Squire": {},
    "Kitain Cross Spear": {},
    "Lion's Roar": {},
    "Lithic Blade": {},
    "Lithic Spear": {},
    "Luxurious Sea-Lord": {},
    "Mailed Flower": {},
    "Makhaira Aquamarine": {},
    "Mappa Mare": {},
    "Missive Windspear": {},
    "Mitternachts Waltz": {},
    "Moonpiercer": {},
    "Mouun's Moon": {},
    "Oathsworn Eye": {},
    "Portable Power Saw": {},
    "Predator": {},
    "Prospector's Drill": {},
    "Prototype Amber": {},
    "Prototype Archaic": {},
    "Prototype Crescent": {},
    "Prototype Rancour": {},
    "Prototype Starglitter": {},
    "Rainslasher": {},
    "Range Gauge": {},
    "Rightful Reward": {},
    "Royal Bow": {},
    "Royal Greatsword": {},
    "Royal Grimoire": {},
    "Royal Longsword": {},
    "Royal Spear": {},
    "Rust": {},
    "Sacrificial Bow": {},
    "Sacrificial Fragments": {},
    "Sacrificial Greatsword": {},
    "Sacrificial Jade": {},
    "Sacrificial Sword": {},
    "Sapwood Blade": {},
    "Scion of the Blazing Sun": {},
    "Serpent Spine": {},
    "Snow-Tombed Starsilver": {},
    "Solar Pearl": {},
    "Song of Stillness": {},
    "Sword of Descension": {},
    "Sword of Narzissenkreuz": {},
    "Talking Stick": {},
    "The Alley Flash": {},
    "The Bell": {},
    "The Black Sword": {},
    "The Dockhand's Assistant": {},
    "The Flute": {},
    "The Stringless": {},
    "The Viridescent Hunt": {},
    "The Widsith": {},
    "Tidal Shadow": {},
    "Toukabou Shigure": {},
    "Wandering Evenstar": {},
    "Wavebreaker's Fin": {},
    "Whiteblind": {},
    "Windblume Ode": {},
    "Wine and Song": {},
    "Wolf-Fang": {},
    "Xiphos' Moonlight": {},
    "Black Tassel": {},
    "Bloodtainted Greatsword": {},
    "Cool Steel": {},
    "Dark Iron Sword": {},
    "Debate Club": {},
    "Emerald Orb": {},
    "Ferrous Shadow": {},
    "Fillet Blade": {},
    "Halberd": {},
    "Harbinger of Dawn": {},
    "Magic Guide": {},
    "Messenger": {},
    "Otherworldly Story": {},
    "Raven Bow": {},
    "Recurve Bow": {},
    "Sharpshooter's Oath": {},
    "Skyrider Greatsword": {},
    "Skyrider Sword": {},
    "Slingshot": {},
    "Thrilling Tales of Dragon Slayers": {},
    "Traveler's Handy Sword": {},
    "Twin Nephrite": {},
    "White Iron Greatsword": {},
    "White Tassel": {},
    "Iron Point": {},
    "Old Merc's Pal": {},
    "Pocket Grimoire": {},
    "Seasoned Hunter's Bow": {},
    "Silver Sword": {},
    "Apprentice's Notes": {},
    "Beginner's Protector": {},
    "Dull Blade": {},
    "Hunter's Bow": {},
    "Waster Greatsword": {},














    "Crimson Moon's Semblance": {
        "id": 0,
        "name": "Crimson Moon's Semblance",
        "description": "",
        "descriptionRaw": "",
        "weaponType": "",
        "weaponText": "Polearm",
        "rarity": 5,
        "story": "",
        "baseAtkValue": 49.1377,
        "mainStatType": "",
        "mainStatText": "CRIT Rate",
        "baseStatText": "4.8%",
        "effectName": "",
        "effectTemplateRaw": "",
        "r1": {
            "description": "",
            "values": []
        },
        "r2": {
            "description": "",
            "values": []
        },
        "r3": {
            "description": "",
            "values": []
        },
        "r4": {
            "description": "",
            "values": []
        },
        "r5": {
            "description": "",
            "values": []
        },
        "costs": {
            "ascend1": [
                {
                    "id": 202,
                    "name": "Mora",
                    "count": 10000
                }
            ],
            "ascend2": [
                {
                    "id": 202,
                    "name": "Mora",
                    "count": 20000
                }
            ],
            "ascend3": [
                {
                    "id": 202,
                    "name": "Mora",
                    "count": 30000
                }
            ],
            "ascend4": [
                {
                    "id": 202,
                    "name": "Mora",
                    "count": 45000
                }
            ],
            "ascend5": [
                {
                    "id": 202,
                    "name": "Mora",
                    "count": 55000
                }
            ],
            "ascend6": [
                {
                    "id": 202,
                    "name": "Mora",
                    "count": 65000
                }
            ]
        },
        "images": {
            "filename_icon": "UI_EquipIcon_Pole_BloodMoon",
            "filename_awakenIcon": "UI_EquipIcon_Pole_BloodMoon",
            "filename_gacha": "UI_EquipIcon_Pole_BloodMoon",
        },
        "version": ""
    },
};